config/routes.rb
Peehere::Application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/rails_admin', :as => 'rails_admin'


  

  match 'locations/:id' => 'locations#show', as: 'location'
  #resources :users
  namespace :admin do
    resources :locations do
      collection do
        get :rate
        post :rate
      end
    end
    resources :ratings
  end

  namespace :api, defaults: {format: 'xml'} do
    resources :users
    resources :locations do
      get :search, :on => :collection
      post :rate,    :on => :collection
      #post :comment, :on => :collection
      get  :places,  :on => :collection
    end
  end

  root :to => "home#index"




  #if Rails.env.development?
    mount ApiTaster::Engine => "/api_taster"
    ApiTaster.routes do
      post '/api/users', {
        :name => 'Fred',
        :email => "fred#{Time.now.to_s.gsub(' ','')}@gmail.com",
      }
      put '/api/users/:id', {}

      # post '/api/locations/rate', {
      #   :user_id => 1,
      #   :location => {
      #     :cache_id => 1,
      #     :description => 'Hay millones de arbustos'
      #   },
      #   :ratings => [
      #     {:kind => 'wait',    :value => [true, false].sample },
      #     {:kind => 'pay',     :value => [true, false].sample },
      #     {:kind => 'paper',   :value => [true, false].sample },
      #     {:kind => 'overall', :value => [true, false].sample }
      #   ]
      # }

      # post '/api/locations/rate', {
      #   :user_id => 1,
      #   :location_id => 1,
      #   :ratings => [
      #     {:kind => 'crowded', :value => [true, false].sample },
      #     {:kind => 'hidden',  :value => [true, false].sample },
      #     {:kind => 'safe',    :value => [true, false].sample },
      #     {:kind => 'overall', :value => [true, false].sample }
      #   ]
      # }

      desc 'params [:location =>  [:address, :latitude, :longitude, :indoor => [true, false], :description, :name, :cache_id] ]'
      post '/api/locations/rate', {
        :user_id => 1,
        :location => {
          :cache_id => nil,
          :description => 'Hay millones de arbustos',
          :name => 'La casucha',
          :indoor => false,
          :latitude => 40.401993,
          :longitude => -3.688660,
          :address => nil,          
        },
        :ratings => {
          :'crowded' => [true, false].sample,
          :'hidden'  => [true, false].sample,
          :'safe'    => [true, false].sample,
          :'overall' => [true, false].sample 
        },
      }

      post '/api/locations/rate', {
        :user_id => 1,
        :location => {
          :cache_id => 1,
          :description => 'Esto deberia sobreescribir descripcion',
          :name => 'Y esto el name',
          :comment => "this is a comment",
        },
        :ratings => {
          :'wait'    => [true, false].sample,
          :'pay'     => [true, false].sample,
          :'paper'   => [true, false].sample,
          :'overall' => [true, false].sample 
        }
      }

      
      #post '/api/locations/comment', {
      #  :user_id => 1,
      #  :location_id => 1,
      #  :comment => "this is a comment"
      #}



      #post '/api/locations/rate', {
      #  :user_id => 1,
      #  :location_id => 1,
      #  :ratings => {
      #    :'crowded' => [true, false].sample,
      #    :'hidden'  => [true, false].sample,
      #    :'safe'    => [true, false].sample,
      #    :'overall' => [true, false].sample
      #  }
      #}


      #desc 'params[:address]'
      #get '/api/locations/search', {
      #  address:'Gran Via 32, Madrid'
      #}

      desc 'params [:address]'
      get '/api/locations/search', {
        address: 'Gran Via 32, Madrid'
      }

      desc 'params [:address, :latitude, :longitude, :show => [:indoor, :outdoor, :all], :distance]'
      get '/api/locations', {
        latitude: 40.4238, 
        longitude: -3.7071,
        show: 'all',
      }

      get '/api/locations', {
        address: 'Gran Via 32, Madrid',
        show: 'all'
      }

      get '/api/locations/:id', {:id => 1}

      desc "params[:latitude, :longitude, :address, :name]"
      get '/api/locations/places', {
        latitude:  40.4238, 
        longitude: -3.7071,        
      }
    end
  #end #if
end

app/models/location.rb
# encoding: UTF-8
class Location < ActiveRecord::Base
  has_many :ratings
  has_many :comments
  #attr_accessor :cache_id
  attr_accessible :address, :average, :description, :indoor, :latitude, :longitude, :name, :cache_id
  serialize :average, Hash
  geocoded_by :address
  # FIXME: sometimes google times out when reverse geocoding, we should retry
  reverse_geocoded_by :latitude, :longitude
  after_validation :geocode_or_reverse_geocode

  DEFAULT_DISTANCE = 1 #in km
  DEFAULT_LIMIT = 10 # return 10 results at most
  VALID_RATINGS_FOR_INDOORS =  [:pay, :wait, :paper, :overall]
  VALID_RATINGS_FOR_OUTDOORS = [:crowded, :hidden, :safe, :overall]

  def self.get_cached_ids
    self.where('cache_id IS NOT NULL').select(:cache_id).map(&:cache_id)
  end

  def self.find_or_create(params)
    if params[:location_id].present?
      Location.find(params[:location_id])
    elsif params[:location][:cache_id].present?
      loc = PlacesCache.find(params[:location][:cache_id]).to_location
      loc.attributes = params[:location]
      loc.save
      loc
    else
      Location.create(params[:location])
    end
  end

  def self.find_by_address_or_coords_and_filter(params)
    locations = Location.scoped
    locations = locations.where(:indoor => true) if params[:show].to_s == 'indoor'
    locations = locations.where(:indoor => false) if params[:show].to_s == 'outdoor'

    near_what = params[:address] if params[:address].present?
    near_what = [params[:latitude], params[:longitude]] if params[:latitude].present? 

    locations = locations.near(near_what, params[:distance] || DEFAULT_DISTANCE)
    locations = locations.order('distance')
    locations = locations.limit(params[:limit] || DEFAULT_LIMIT)
  end

  def update_statistics!
    self.update_average
    self.update_people_count
    # FIXME: a save in this model might trigger a geocode or reverse_geocode call to Google
    # this should be avoided
    self.save
  end

  def update_people_count
    # self.people_count = self.ratings.group(:user_id).length
    self.people_count = self.ratings.select('ratings.id, ratings.user_id').group_by(&:user_id).length
  end

  def update_average
    if self.indoor?
      self.average = calculate_indoor_average
    else
      self.average = calculate_outdoor_average
    end
  end

  def calculate_indoor_average
    {
      pay:     Rating.average_for_kind('pay',     self.id),
      wait:    Rating.average_for_kind('wait',    self.id),
      paper:   Rating.average_for_kind('paper',   self.id),
      overall: Rating.average_for_kind('overall', self.id)
    }
  end

  def calculate_outdoor_average
    {
      crowded: Rating.average_for_kind('crowded', self.id),
      hidden:  Rating.average_for_kind('hidden',  self.id),
      safe:    Rating.average_for_kind('safe',    self.id),
      overall: Rating.average_for_kind('overall', self.id)
    }
  end

  def geocode_or_reverse_geocode
    if address
      geocode
    else
      reverse_geocode
    end
  end

  #def valid_ratings?(params)
  #  if self.indoor?
  #    params.all?{ |rating| VALID_RATINGS_FOR_INDOORS.include?(rating[:kind].to_sym) }
  #  else
  #    params.all?{ |rating| VALID_RATINGS_FOR_OUTDOORS.include?(rating[:kind].to_sym) }
  #  end
  #end

  def valid_ratings?(params)
    return true if params.blank?
    if self.indoor?
      params.keys.all?{ |kind| VALID_RATINGS_FOR_INDOORS.include?(kind.to_sym) }
    else
      params.keys.all?{ |kind| VALID_RATINGS_FOR_OUTDOORS.include?(kind.to_sym) }
    end    
  end

  def to_xml(options={})
    #options.merge!(include: :comments)
    options.merge!(:except => [:created_at, :updated_at], :methods => :comments_html)    
    super(options)
  end

  def comments_html
    comments.map(&:to_html).join("<br />")
  end
  



  def to_tweet
    url = Rails.application.routes.url_helpers.location_url(self)
    url = 'http://pee-here.com'
    "http://twitter.com/home?status=#{random_tweet} #{CGI::escape(url)} @peehere"
  end

  def random_tweet
    @@possible_tweets.sample
  end
  @@possible_tweets = [
    "Don't worry, pee happy",
    "Orina como en casa",
    "Orina en publico como si estuvieses en casa",
    "Llego la aplicación móvil para que orines donde mas te guste.",
    "Orina a domicilio", 
    "Pee Here. Orina donde quieras",
    "Psssss. Necesitas ir al baño? Pee Here esta desocupado",
    "Te estas orinando? Pee Here te echa una mano",
    "Ven a orinar con nosotros",
    "Lugares orinables full time",
    "Si te estas por mear, meate con nosotros",
    "Orina aquí. Y ahí. Tambien allí",
    "Libera la orina que llevas en ti",
    "Tenemos el lugar indicado para que satisfagas tus necesidades",
    "En apuros? Lo siento", 
    "En Pee Here sabemos donde hay papel higienico",
    "No esperes, Pee Here",
    "You’ll never pee alone",
    "Programa tu orina",
    "Support your team with our app",
    "In peeing we believe",
    "Te estas meando? Vete al baño",
    "Pee Here: mobile bathrooms",
    "Te damos un chocolate por cada descarga",
    "Pruebanos  y si no te convence te devolvemos la orina sin ningún cargo",
    "Si descargas Pee Here te comentaremos las fotos del Facebook que menos feedback hayan tenido",
    "Te queremos. Ver mear",
    "Velamos por la seguridad de tu orina",
    "Para cuando tengas necesidades en la calle, Pee Here",
    "Pee here te evita infecciones de orina",
    "Seis de cada diez personas recomienda que “orinar” es saludable. Somos mayoría.",
    "Esto es una dictadura: te obligamos a que orines en uno (o todos) nuestros lugares públicos.",
    "Tu novio te engaña? Ok, solo por esta vez te dejamos que nos cambies: Pee on Him.",
    "Vente de gira con Pee Here. Haremos botellón en el lugar publico mas votado",
    "Si te estas orinando, nos querras en tus manos",
    "Antes de mear necesitaras saber el lugar",
    "Si nuestra App no te sirve, vendemos papel higienico o te prestamos un Kleenex a un euro",
    "Ya sabes el lugar, solo dale a “Confirmar”",
    "Porque el bano es el espacio mas intimo, Pee Here te hace de mejor amigo o de momento reflexivo",
  ]



end

app/controllers/admin/locations_controller.rb
module Admin
  class LocationsController < ApplicationController
    #http_basic_authenticate_with(:name => "wepeehere", :password => "dickface123") unless Rails.env.development?
    before_filter :ensure_current_user_is_admin

    def index
      @locations = Location.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @locations }
      end
    end

    def show
      @location = Location.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @location }
      end
    end

    def new
      @location = Location.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @location }
      end
    end

    def edit
      @location = Location.find(params[:id])
    end

    def create
      @location = Location.new(params[:location])

      respond_to do |format|
        if @location.save
          format.html { redirect_to @location, notice: 'Location was successfully created.' }
          format.json { render json: @location, status: :created, location: @location }
        else
          format.html { render action: "new" }
          format.json { render json: @location.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      @location = Location.find(params[:id])

      respond_to do |format|
        if @location.update_attributes(params[:location])
          format.html { redirect_to @location, notice: 'Location was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @location.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @location = Location.find(params[:id])
      @location.destroy

      respond_to do |format|
        format.html { redirect_to locations_url }
        format.json { head :no_content }
      end
    end

    def rate
      if request.post?
        loc  = Location.find_or_create(params)
        user = current_user
        ratings = user.create_ratings(loc, params[:ratings])
        loc.update_statistics!
        redirect_to loc
      else
        @location = Location.find_by_id(params[:id]) || Location.new(indoor:params[:indoor])
        render :rate      
      end
    end
  end
end

app/controllers/api/locations_controller.rb
module Api
  class LocationsController < ApplicationController
    # params [:address, :latitude, :longitude, :show => [:indoor, :outdoor, :all], :distance]
    def index
      locations = Location.find_by_address_or_coords_and_filter(params)
      respond_to do |format|
        format.xml  { render :xml  => locations }
        format.json { render :json => locations }
      end
    end

    def search
      locations = Location.near(params[:address]).order('distance').limit(10)
      google_places = PlacesCache.find_places(params)
      results = (locations + google_places).uniq
      
      respond_to do |format|
        format.xml  { render :xml  => results.to_xml }
        format.json { render :json => results }
      end      
    end

    def show
      loc = Location.find(params[:id])
      respond_to do |format|
        format.xml  { render :xml  => loc }
        format.json { render :json => loc }
      end
    end

    def rate
      comment_text = params[:location].delete(:comment) if params[:location].present? && params[:location][:comment].present?
      loc  = Location.find_or_create(params)
      user = User.find(params[:user_id])
      comment = Comment.create(location_id:loc.id, user_id:user.id, body:comment_text) if comment_text.present? 
      ratings = user.create_ratings(loc, params[:ratings])
      loc.update_statistics!

      respond_to do |format|
        format.xml  { render :xml  => {url:loc.to_tweet} }
        format.json { render :json => ratings }
      end      
    end

    #def comment
    #  loc  = Location.find(params[:location_id])
    #  user = User.find(params[:user_id])
    #  comment = Comment.create(location_id:loc.id, user_id:user.id, body:params[:comment]) if params[:comment]
    #  respond_to do |format|
    #    format.xml  { render :xml  => comment }
    #    format.json { render :json => comment }
    #  end            
    #end

    # por lat, long o por address o por name
    # devolver restaurantes / bares cercanos
    def places
      locations = PlacesCache.find_places(params)
      respond_to do |format|
        format.xml  { render :xml  => locations.to_xml }
        format.json { render :json => locations }
      end
    end

  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def show
    @location = Location.find(params[:id])
    @comments = @location.comments
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
  def icon_for(location)
    if location.indoor?
      image_tag 'images/toilette.png'
    else
      image_tag 'images/tree.png'
    end
  end
end

app/views/admin/locations/_form.html.haml
= form_for @location, url: @location.new_record? ? new_admin_location_path : admin_location_path(@location)  do |f|
  -if @location.errors.any?
    #error_explanation
      %h2= "#{pluralize(@location.errors.count, "error")} prohibited this location from being saved:"
      %ul
        - @location.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :address
    = f.text_field :address    
  .field
    = f.label :latitude
    = f.text_field :latitude
  .field
    = f.label :longitude
    = f.text_field :longitude
  .field
    = f.label :indoor
    = f.check_box :indoor

  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'
-#  .field
-#    = f.label :latitude
-#    = f.text_field :latitude
-#  .field
-#    = f.label :longitude
-#    = f.text_field :longitude
-#  .field
-#    = f.label :indoor
-#    = f.check_box :indoor
-#  .field
-#    = f.label :address
-#    = f.text_field :address
-#  .field
-#    = f.label :description
-#    = f.text_area :description
-#  .field
-#    = f.label :name
-#    = f.text_area :name
-#  .field
-#    = f.label :average
-#    = f.text_area :average
-#  .field
-#    = f.label :cache_id
-#    = f.number_field :cache_id
-#  .field
-#    = f.label :people_count
-#    = f.number_field :people_count

app/views/admin/locations/create.html.haml
%h1 Locations#create
%p Find me in app/views/locations/create.html.haml

app/views/admin/locations/edit.html.haml
%h1 Editing location

= render 'form'

= link_to 'Show', @location
\|
= link_to 'Back', admin_locations_path

app/views/admin/locations/index.html.haml
%h1 Listing locations

%table
  %tr
    %th Latitude
    %th Longitude
    %th Indoor
    %th Address
    %th Description
    %th Name
    %th Average
    %th Cache
    %th People count
    %th
    %th
    %th

  - @locations.each do |location|
    %tr
      %td= location.latitude
      %td= location.longitude
      %td= location.indoor
      %td= location.address
      %td= location.description
      %td= location.name
      %td= location.average
      %td= location.cache_id
      %td= location.people_count
      %td= link_to 'Show', admin_location_path(location)
      %td= link_to 'Edit', edit_admin_location_path(location)
      %td= link_to 'Destroy', admin_location_path(location), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Location', new_admin_location_path

app/views/admin/locations/new.html.haml
%h1 New location

= render 'form'

= link_to 'Back', locations_path

app/views/admin/locations/rate.html.haml
%h1 New location #{@location.indoor ? 'indoor' : 'outdoor'}
- indoor = @location.indoor
= form_for @location, url: rate_admin_locations_path, method:'post' do |f|
  -if @location.errors.any?
    #error_explanation
      %h2= "#{pluralize(@location.errors.count, "error")} prohibited this location from being saved:"
      %ul
        - @location.errors.full_messages.each do |msg|
          %li= msg
  - unless @location.new_record?
    = hidden_field_tag :location_id, @location.id
  .field
    = f.label :name
    = f.text_field :name
  - if indoor
    .field
      = f.label :address
      = f.text_field :address    
  - else
    .field
      = f.label :latitude
      = f.text_field :latitude
    .field
      = f.label :longitude
      = f.text_field :longitude
  = f.hidden_field :indoor, value:indoor

  .field
    = f.label :description
    = f.text_field :description

  - if indoor
    - variables_to_rate = Location::VALID_RATINGS_FOR_INDOORS
  - else
    - variables_to_rate = Location::VALID_RATINGS_FOR_OUTDOORS
  - variables_to_rate.each do |variable|
    .field
      = label_tag variable
      %p 
        yes
        = radio_button_tag "ratings[#{variable}]", "true"
        \|
        no
        = radio_button_tag "ratings[#{variable}]", "false"
        \|
        don't know
        = radio_button_tag "", nil, true
      %br






  .actions
    = f.submit 'Save'

= link_to 'Back', admin_locations_path

app/views/admin/locations/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @location.name
%p
  %b Description:
  = @location.description

- if @location.indoor?
  %p
    %b Address:
    = @location.address
- else
  %p
    %b Latitude:
    = @location.latitude
  %p
    %b Longitude:
    = @location.longitude
%p
  %b Indoor:
  = @location.indoor
%p
  %b Average:
  = @location.average
%p
  %b Cache:
  = @location.cache_id
%p
  %b People count:
  = @location.people_count

:css
  table tr th, table tr td {text-align:center}

%table
  %thead
    %tr
      %th id
      %th user_id
      %th kind
      %th value
  %tbody
    - @location.ratings.each do |rating|
      %tr
        %td= link_to rating.id, admin_rating_path(rating)
        %td= rating.user_id
        %td= rating.kind
        %td= rating.value

= link_to 'Edit', edit_admin_location_path(@location)
\|
= link_to 'Back', admin_locations_path
\|
= link_to 'rate', rate_admin_locations_path(id:@location.id)